name: Upload Web Static Files And Server Files

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-server:
    name: SFTP Node Server Files To Centos
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Resources
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.CENTOS_HOST }}
          user: ${{ secrets.CENTOS_USER }}
          pass: ${{ secrets.CENTOS_PASSWORD }}
          connect_timeout: 60s
          first_ssh: |
            cd /home/www
            rm -rf anyphoto-server
            mkdir anyphoto-server
          scp: |-
            ./server/* => /home/www/anyphoto-server/
            ./server/.env.vault => /home/www/anyphoto-server/
          last_ssh: |
            source /etc/profile
            cd /home/www/anyphoto-server
            pnpm i
            pnpm run start:production
